---
- name: 웹 서버 설정과 인증 페이지 구성
  hosts: all
  vars_files:
    - vars/vars.yml
  tasks:
    # 1) 패키지 설치 - firewalld, httpd, mod_ssl
      - name: 1) 패키지설치
        ansible.builtin.yum:
          name: "{{ pkgs }}"
          state: present
          
        

    # 2) /etc/httpd/conf/httpd.conf
    # 3) /var/www/html/.htaccess /생성
    # 4) /etc/httpd/secrets/htpasswd/ 생성
    # 5) /etc/httpd/secrets/htpasswd 생성
    # 6) /var/www/html/index.html
      - name: 2-1) httpd.conf 파일 설정
        ansible.builtin.copy:
          src: "{{ conf_web_src }}"
          dest: "{{ conf_web_dst }}"
          owner: root
          group: root
          mode: '0644'
      
      - name: 2-2) .htaccess 파일 설정
        ansible.builtin.copy:
          src: "{{ htaccess_src }}"
          dest: "{{ htaccess_dst }}"
          owner: apache
          group: apache
          mode: '0400'

      - name: 2-3) /etc/httpd/secrets 디렉토리 생성
        ansible.builtin.file:
          path: /etc/httpd/secrets
          state: directory
          mode: apache
          owner: apache
          mode: '100'

      - name: 2-4) /etc/httpd/secrets/htpasswd
        ansible.builtin.copy:
          src: "{{ htpasswd_src }}"
          dest: "{{ htpasswd_dst }}"
          owner: apache
          group: apache
          mode: '0400'

      - name: 2-5) /var/www/html/index.html
        ansible.builtin.copy:
          content: "{{ ansible_fqdn }} : {{ ansible_all_ipv4_addresses }}" 
          dest: "{{ mainpage }}"
          mode: '0644'

    # 7) httpd, firewalld 서비스 기동
      - name: 3)서비스 기동
        ansible.builtin.service:
          name: "{{ item }}"
          state: stopped
          enabled: false
        loop: "{{ svcs }}"

    # 8) 방화벽 등록 - http, https 
      - name: 4) 방화벽 포트 등록 해제
        ansible.posix.firewalld:
          service: "{{ item }}"
          permanent: true
          immediate: false
          state: disabled
        loop: "{{ fw_svcs }}"

