---
- name: Restore playbook.yml
  hosts: all
  gather_facts: true
  vars:
    pkg_fw: firewalld
    svc_fw: firewalld
    svcs_fw:
     - http
     - https
  tasks: 
    # 1) 방화벽 포트 제거 - http,https
    # 2) 서비스내리기 - httpd, mariadb ( 방화벽은 내릴 필요 없음)
    # 3) 설정 삭제 -/var/www/html/index.html
    # 4) 패키지 삭제 - httpd, mariadb-server 

  - name: 1) 방화벽에 포트 제거
    ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: false
        immediate: false
        state: disabled
    loop: "{{ svcs_fw }}"

  - name: 2) 서비스내리기 
    ansible.builtin.service:
     name: "{{ svc_fw }}"
     state: stopped
     enabled: false

  - name: 서비스 설정 해제
    ansible.builtin.file:
      path: /var/www/html/index.html
      state: absent

  - name: 4) 패키지 삭제
    ansible.builtin.dnf:
      name: "{{ pkg_fw }}"
      state: absent





