---
- name: Task Failure Exercise
  hosts: databases
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb
  tasks:    
    - name: remove {{ web_package }} package
      ansible.builtin.yum:
        name: "{{ web_package }}"
        state: absent
      
    - name: remove {{ db_package }} package
      ansible.builtin.yum:
        name: "{{ db_package }}"
        state: absent
            
