---
- name: 0) 잡제어
  hosts: webservers
  gather_facts: true
  vars_files:
    - vars.yml
  tasks:
    # 1) 정보 수집 & 필수 사양 점검
    # 2) 패키지 설치 -httpd, mod_ssl, firewalld
    # 3) 서비스 기동 - httpd, firewalld
    # 4) 웹 서버 HTTPS 설정 - notify ~ handlers
    # 5) 방화벽 포트 열기
  # 6) handlers
###################################################
    # 1) 패키지 설치 -httpd, mod_ssl, firewalld
  - name: 1) 패키지 삭제
    ansible.builtin.dnf:
      name: "{{ packages }}"
      state: absent
    # 2) 서비스 기동 - httpd, firewalld
  - name: 2) 서비스 기동 해제
    ansible.builtin.service:
      name: "{{ item }}"
      state: stopped
      enabled: false
    loop: "{{ services }}"
    # 4) 웹 서버 HTTPS 설정 - notify ~ handlers:
    # * /et/pki/tls/certs/localhost.crt
    # * /etc/pki/tls/private/localhost.key
    # . /var/www/html/index.html
  - name: 4) 웹서버 https 설정
    block:
    - name: 4-1)설정 파일 배포
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop: "{{ web_config_files }}"   
      notify: restart_web
    rescue:
      - name: 4-2)설정 파일 배포 에러 메세지 출력
        ansible.builtin.debug:
          msg: "하나 이상의 설정 파일 배포에 문제가 발생함"

  #5) 방화벽 포트 열기
  - name: 5) 방화벽 포트 등록 
    ansible.posix.firewalld:
      service: "{{ item }}"
      permanent: true
      immediate: true
      state: disabled
    loop:
      - http
      - https


  # 6) handlers
  handlers:
    - name: restart_web
      ansible.builtin.service:
        name: "{{ web_service }}"
        state: restart
    

